FROM node:12.18.3

WORKDIR /usr/src/libra-server

COPY ./ ./

RUN npm install

CMD ["/bin/bash"]

# docker build -it [containerName] .
# docker run -it [containerName]
# docker ps
# docker exec -it [fce327792a88] bash
# docker stop -it [fce327792a88]